#FROM ghcr.io/commaai/openpilot-base:latest
#FROM openpilot-base-cudnn
FROM openpilot-base

#BUILD COMMAND: docker build -f Dockerfile.openpilot -t openpilot .

ENV PYTHONUNBUFFERED=1

ENV OPENPILOT_PATH=/home/batman/openpilot
ENV PYTHONPATH=${OPENPILOT_PATH}:${PYTHONPATH}

RUN mkdir -p ${OPENPILOT_PATH}
WORKDIR ${OPENPILOT_PATH}

COPY . ${OPENPILOT_PATH}/

RUN scons --cache-readonly -j$(nproc)
